added react setup
hasnatali1947/Calculator pull request #1
Opened 2023-04-25 20:08 UTC by hasnatali1947

2023-04-25 21:18 UTC, prolajumokeoni requested changes
Hi @hasnatali1947 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- React app created with Create React App ✅  




## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 21:18 UTC, prolajumokeoni commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Kindly add the MIT license for your project this will make your readme more professional, you can do it here on [Github](https://github.com/hasnatali1947/Calculator/community/license/new?branch=development&filename=LICENSE&template=mit)

2023-04-26 05:15 UTC, amejid requested changes
Hi @hasnatali1947, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/>

 ## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Gitflow :heavy_check_mark: 
- App created with CRA :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 05:15 UTC, amejid commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] The MIT license link is broken because you are referencing `LICENSE` while your file is named `MIT.md`. 🤝️

![image](https://user-images.githubusercontent.com/17243325/234475617-00e197d2-e64d-416c-9eef-1b94f786ec73.png)

Try the following to fix the issue.

```
This project is [MIT](./MIT.md) licensed.
```

2023-04-26 05:32 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @hasnatali1947 

Your project is complete! Great job 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 05:32 UTC, tufoinnkuo10 commented on README.md
> +<!-- LIVE DEMO -->
- [optional] you can remove the live demo section since your project is yet to be deployed. this can be added later on

2023-04-26 09:26 UTC, merged